### ISSUE TITLE
로컬스토리지 삭제 시 clear() vs removeItem('item')

### ISSUE THREAD

**Issue by bm4656** [Mogakco-web/FE-Mogakco#12]
로그아웃 시 로컬스토리지에 있는 토큰(accessToken, refreshToken, authToken)을 삭제하는데 
`localStorage.clear();` 를 사용해 다 비우는 것이 좋을지 `localStorage.removeItem('authToken');`처럼 하나하나 지울지 어떤게 이득일지 고민입니다.

**Comment by Siby1lA** [comment]
제 의견은 `clear()`로 도메인 내의 모든 로컬스토리지를 비우는 것도 좋으나, 추후 로컬스토리지에 다른 값도 저장할 가능성이 있어 `removeItem()` 로 지우는게 좋다고 생각합니다!

**Comment by bm4656** [comment]
@Siby1lA zustand-persist 로 로그인 유저 상태와 유저 정보 일부를 저장하므로 로컬스토리지를 이용하게 되는데 이 값들도 한 번에 지우기 용이할 것 같아서 clear()를 사용해봤습니다.  persist를 사용하지 않고 토큰의 유무로 로그인 상태를 확인하는 훅을 만들어 렌더링 시 확인하는게 더 좋을까요?

**Comment by Siby1lA** [comment]
@bm4656  저는 후자가 취향이긴 한데 정답은 아니므로 보민님이 좋아하는 방식으로 하시면 될 거 같아요!!
