### ISSUE TITLE
ApiController에서 토큰 null 인식 이슈

### ISSUE THREAD

**Issue by bm4656** [Mogakco-web/FE-Mogakco#13]
ApiController에서 토큰 null 인식 시 
if문에서 그냥 null 로만 하면 정말 로컬스토리지에도 없는 null일 때는 작동하지만 로컬스토리지에는 키값은 있지만 value가 null 일땐 인식을 못합니다. 그래서 문자열 'null'도 추가를 해주니 동작했습니다.
왜 이런지 알아봐야할 것 같고 더 좋은 방법이 있을 지 토론해보면 좋을 것 같습니다.
```js
axios.interceptors.request.use((requestConfig: AxiosRequestConfig) => {
  const accessToken: string | null = localStorage.getItem('accessToken');
  const authToken: string | null = localStorage.getItem('authToken');
  if (authToken === 'null' || authToken === null) {
    console.log(authToken);
    requestConfig.headers = {
      Authorization: `Bearer ${accessToken}`,
      userInfo: `${accessToken} `,
    };
  } else {
    console.log('&', authToken);
    requestConfig.headers = { Authorization: `Bearer ${accessToken}` };
  }
  return requestConfig;
});
```

**Comment by Siby1lA** [comment]
보통 키-밸류의 데이터를 가진 변수는 값을 비교할 때 밸류값을 기준으로 비교하게 되는데 authToken의 밸류가 'null'인 상태라서 `if(authToken === 'null')`이 조건을 써야 동작했던 것으로 보입니다. 

여기서 왜 authToken의 밸류가 'null' 이냐면, localstorage는 string형의 데이터만 저장할 수 있기 때문입니다.

다른 방법으로는 로컬스토리지에 저장된 토큰값이 없을 때보다는 대개 토큰을 재요청하는 이유는 서버에서 토큰의 유효기간이 끝났을 때이므로
서버에서 요청된 리소스에 대한 유효한 인증 자격 증명이 없을 때 401에러가 뜨는데 이 에러가 발생했을 때 재요청하는 것도 좋은 방법이라고 생각합니다.

**Comment by bm4656** [comment]
@Siby1lA 풍부한 답변 감사합니다. localstorage는 string형의 데이터만 저장할 수 있다는 사실을 망각했었네요!

현재 프로젝트에서는 깃허브 Oauth + 자체JWT 사용으로 인해 
1. 로그인 성공 시 accessToken, refreshToken 발급 ->  로컬스토리지에 저장
2. 저장과 동시에 유저정보 받아오는 함수 동작 ->`authToken(깃허브 Oauth 인증 토큰)` 로컬스토리지에 저장(핵심! 이것 때문에 이 함수가 존재하는 것), 간단한 정보(유저이미지,유저이름) zustand에 저장
3. 마이페이지에서 상세한 유저 정보는 새로 요청
4. 로그아웃 시 토큰 인증 필수인 accessToken를 헤더에 담고 authToken(깃허브 Oauth 인증 토큰, 로그아웃 시 필수)을 전달해 로그아웃 요청

이러한 방식으로 진행되고 있습니다.
현재 axios intercepter를 사용하여 api request 시 토큰 유효 인증을 한 번에 처리하고 있는데,
유일하게 첫 로그인 시 1번 과정 이후 2번 동작 시  서버에서 이 정보요청이 어떤 유저의 요청인지 찾기 위한 값인 authToken이 필요합니다(accessToken은 인증용이므로  필터링 부적합). 이 경우에만 헤더에 요청이 아래와 같이 되어야하므로
```
requestConfig.headers = {
      Authorization: `Bearer ${accessToken}`,
      userInfo: `${accessToken} `,
    };
```
`if(authToken === 'null')` 와 같은 분기를 사용했던 것입니다. 

서버에서 요청된 리소스에 대한 유효한 인증 자격 증명이 없을 때 401에러를 이용한 토큰 재발급 로직은 현재 코드 구현 중입니다. 다시 한 번 답변 감사드립니다.👍
