### ISSUE TITLE
타이머 기록시 자정이 넘어갔을 경우 저장방법에 대해서

### ISSUE THREAD

**Issue by Siby1lA** [Mogakco-web/FE-Mogakco#19]
# 🔥 이슈
자정(24시)이 넘어가는 경우 기록을 어떻게 해야하는지 여러 방법과 그에 따른 기술적인 문제에 대한 이슈
1. 연속 모드 : 자정이 넘어서도 시간이 이어서 기록된다.
2. 누적 모드: 하루 마다 시간이 관리된다. 즉 자정이 넘으면 0초로 초기화

# 1. 연속 모드

## 장점 
1. 개발자는 대게 밤에 공부하는 사람이 많아 자정이 넘어서까지 기록을 하는게 좋다.
## 단점
1. 자정이 넘어가면 기록된 날짜를 언제로 해야할지 애매모호하다. (타이머 시작한 날, 타이머 중지한 날)
2. 타이머 중지한 날이 자정이 넘어가면 API 보낼때 전날인지, 다음날인지 어떻게 알고 데이터를 보내야하는지(자정 캐치 로직 고민)
3. 자정이 넘어가서 타이머를 중지하고 다시 시작할때 전날인지 다음날인지에 대한 이슈

## 기술적인 문제
- 자정이 넘어갔을 때 사용자가 타이머 중지 버튼을 누르고, 다시 시작하면 다음날로 타이머가 초기화된다.

# 2. 누적 모드
## 장점
1. 자정이 넘으면 0초로 초기화 되니 날짜별로 기록 데이터를 관리하기 편리하고 랭킹집계에도 편리하다.
## 단점 
1. 자정 앞뒤로 공부하는 사람들에게는 갑자기 자정에 시간이 초기화 되어서 얼마만큼 공부했는지 보여주는 사용자 경험에 대해 안좋은 상황이 생긴다.

## 기술적인 문제
- 자정을 캐치하는 로직을 어떻게 짜야하는지 고민해봐야 한다.

# 결론
**연속모드, 누적모드 어떠한 방법을 써야하는지에 대해서이며 그에 따른 구현방법과 기술적인 문제**(어려움) 대해 토론해봐야 한다.

**Comment by Siby1lA** [comment]
저는 1번의 연속 모드를 하는게 좋아보입니다.
타이머 중지할 때, 타이머 시작 날짜와 중지 날짜를 캐치해서, 시작 날짜를 서버로 보내면 시작 날짜로 데이터가 저장될거라고 생각합니다.
다만 타이머 중지하고 다시 시작할때에 대한 문제가 생기는데, 이는 클라이언트에서만 처리하는 일시정지 버튼을 만들고 이 버튼은 서버로 데이터를 전송하지 않는 것입니다. 
결론은 클라이언트에서만 돌아가는 로직인 일시정지 버튼을 만들고, 일시정지 버튼이 아닌 정지 버튼을 누를 때만 서버로 데이터를 보내면 될 거 같습니다.

**Comment by seonghoo1217** [comment]
@Siby1lA  맞습니다. 연속 모드를 지향해야하는 것은 맞으나 현재 기술적인 문제가 존재합니다. 결국 정지버튼을 누르는 시점과 타이머가 생성된 시점이 다르다면 이를 서버측에서 처리하는 데 문제가 발생합니다.

예를 들어 아래 상황을 가정해보겠습니다.
- 타이머 생성 날짜 : 2023-03-21
- 타이머 종료 날짜 : 2023-03-22

만약 위와 같이 가정한다면 서버측에서는 `timerCreDay`라는 타이머 생성날짜를 기점으로 비즈니스 로직을 구현하기 때문에, 종료날짜가 다르게 온다면 새로운 데이터가 생성되거나 DB에 **존재하지 않는 데이터**를 찾으려하기에 에러가 날 것으로 생각합니다.

**Comment by Siby1lA** [comment]
@seonghoo1217 
연속 모드의 타이머 시작, 중지 날짜 캐치 로직은 프론트에서 할 수 있을거 같습니다.

타이머 생성시 로컬이나 쿠키에 생성 날짜를 저장한 다음,
타이머 중지시 중지 날짜를 받아와 생성날짜가 있다면 생성날짜를 서버로 보내는 것입니다.

이렇게 하게 되면 타이머의 시간과 중지 날짜를 캐치해서 시간 날짜를 보낼 수 있을 것입니다.

**Comment by seonghoo1217** [comment]
@Siby1lA 해당 이슈와 더불어 타이머 페이지 입장 시 해당 날짜와 회원 정보에 맞추어 시간정보를 0으로 모두 초기화합니다.
이후 정지 버튼을 눌러 API를 호출할 경우 이를 Update시키는 방법을 사용하고 있습니다.  그럼 초기화 로직을 제거하고 중지버튼 로직 하나만을 계속 유지하여야 할까요? 아니면 초기화 로직은 구현하되, 이후 업데이트 방식만을 사용하여야 할까요?

**Comment by Siby1lA** [comment]
@seonghoo1217
페이지 입장시 호출하는 api는 `/api/v1/timer/todayInfo`.
이 로직은 날마다 0초로 초기화 되는데, 연속 모드로 자정이 넘어가도 시간이 지속되어 해당 타이머 페이지 재 접속시 0으로 초기화 되니 발생하는 이슈로 이해했습니다.

혹시 말씀하신 `초기화 로직은 구현하되, 이후 업데이트 방식`에 더 대해 자세히 알려주실 수 있나요?

**Comment by seonghoo1217** [comment]
@Siby1lA 현재 `Timer Page` 입장 시 값을 초기화 할 것을 고려해 새로운 API인 `/api/v1/timer/initialize`를 제작하였습니다.

해당 API는 `timerCreDay`와 `oauthId` 만을 받아 DB에 값을 초기화합니다.

제가 생각하는 로직은 `Timer Page`가 조회 되었을 때 항상 `/api/v1/timer/todayInfo`를 호출하여 분기 처리를 할 수 있는지를 물어보고자 하는 의도였습니다.

**Comment by Siby1lA** [comment]
결론 :
입장 시 값을 초기화 하기 위한 APi인 `/api/v1/timer/initialize` 를 추가하지 않고, 로직을 아래와 같이 하기로 결론.
ex) 
- 사용자가 타이머 시작을 누른 시간 23:00시, 시작시 현재 날짜 데이터를 localstorage에 저장.
- 사용자가 타이머 정지를 누른 시간 00:30시, 정지를 누를때 현재 날짜 데이터를 가져옴,
시작의 날짜와 중지의 날짜를 비교해, 중지 날짜가 더 크면 자정을 넘어서 타이머를 기록한 것이므로 시작 날짜로 백엔드에게 보낸다.
보냄과 동시에 저장된 localstroage의 시작 데이터는 삭제.

이렇게 하면 사용자가 자정이 넘어 타이머를 기록했어도 그 날 잠을 자고 일어나서 아침에 다시 하더라도, 새로운 날짜로 업데이트 되어서 알맞은 로직이 된다.

다만, 이렇게 하기 위해서 중지 버튼 이외에 일시정지 버튼을 만들어야 한다.
